export enum InputSuffixCompName  {
  TextField = 'TextField',
  SecretField = 'SecretField',
  UrlField = 'UrlField',
  Password = 'Password',
  TextArea = 'TextArea',
  IntlField = 'IntlField',
  EmailField = 'EmailField',
  NumberField = 'NumberField',
  Currency = 'Currency',
  DatePicker = 'DatePicker',
  Cascader = 'Cascader',
  Select = 'Select',
  AutoComplete = 'AutoComplete',
  Lov = 'Lov',
  TreeSelect = 'TreeSelect',
  ColorPicker = 'ColorPicker',
  IconPicker = 'IconPicker',
}
